name: order

services:

  postgres:
    image: postgres:16.0
    container_name: order-postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./db_order :/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  keycloak-postgresql:
    image: postgres:16.8
    restart: always
    ports:
      - 5435:5432
    volumes:
      - ./db_keycloak :/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  order-be:
    image: localhost:5000/order_service:1.0.0
    container_name: order-service-be
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: jdbc:postgresql://order-postgres:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: example
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    command: start-dev
    restart: always
    ports:
      - 8081:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_SPI_ADMIN_REALM: master
      KEYCLOAK_HTTP_RELATIVE_PATH: /

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgresql:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    depends_on:
      keycloak-postgresql:
        condition: service_healthy

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    restart: always
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_PASSWORD: ChangeMe123!
      SPLUNK_HEC_TOKEN: "11111111-2222-3333-4444-555555555555"
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - ./splunk-data:/opt/splunk/var
      - ./splunk-etc:/opt/splunk/etc