name: order

services:

  postgres:
    image: postgres:16.0
    container_name: order-postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./db_order :/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
  order-be:
    image: order_service:1.0.0
    container_name: order-service-be
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_URL: jdbc:postgresql://order-postgres:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: example
    depends_on:
      - postgres