spring.application.name=order-service

server.port=3000

# postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:example}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.root=INFO

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:/resources/db/migration
spring.flyway.url=${DB_URL:jdbc:postgresql://localhost:5434/postgres}
spring.flyway.user=${DB_USER:postgres}
spring.flyway.password=${DB_PASSWORD:example}
spring.flyway.schemas=postgres

# Actuator - ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include=info, health, metrics

management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true

# Actuator - HEALTH ENDPOINT
#best practice 'when_authorized' per health
management.endpoint.health.show-details=when_authorized

# Actuator - INFO ENDPOINT CONFIGURATION
management.info.env.enabled=true
info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@

#Keycloak (es. http://localhost:8080)
keycloak.auth-server-url=http://localhost:8081
keycloak.realm=foodmanager

# Registration
spring.security.oauth2.client.registration.nsa2-gateway.provider=keycloak
spring.security.oauth2.client.registration.nsa2-gateway.client-id=foodmanager
spring.security.oauth2.client.registration.nsa2-gateway.client-secret=BP9654GivSS4Ly028TutmIDKByOXlz9967ECW5QazEsEDa0O7hBEBNiFHRcfnHfsX94ddijxNuZiiS71mAWmSt
spring.security.oauth2.client.registration.nsa2-gateway.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.nsa2-gateway.scope=openid,profile,email
spring.security.oauth2.client.registration.nsa2-gateway.redirect-uri=${NSA2_OAUTH_REDIRECT_URI:http://localhost:63342/*, http://localhost:3000/*}
spring.security.oauth2.client.registration.nsa2-gateway.client-name=Foodmanager Gateway
spring.security.oauth2.client.registration.nsa2-gateway.client-authentication-method=client_secret_basic

# Provider
spring.security.oauth2.client.provider.keycloak.issuer-uri=${NSA2_OAUTH_ISSUER_URI:http://localhost:8081/realms/foodmanager}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

